import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect("10.176.60.72", username="jiaqigu", password="lijia7272", timeout=10)
_, o, _ = c.exec_command("tail -15 /home/jiaqigu/mrrate_hidnet/outputs/report_gen/phase2.log 2>&1")
print("LOG:", o.read().decode())
_, o, _ = c.exec_command("ps aux | grep train_v5 | grep python | grep -v grep | head -2")
print("PROC:", o.read().decode().strip() or "none")
_, o, _ = c.exec_command("ls -la /home/jiaqigu/mrrate_hidnet/outputs/report_gen/phase2.log 2>&1")
print("FILE:", o.read().decode().strip())
c.close()
